<a href="https://colab.research.google.com/github/chennareddyb/python_training/blob/Feb2025/part1_04Feb25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
sslc = pd.read_csv('marks.txt', sep=';', header=None, index_col=None)
print(sslc)

       0       1    2    3   4   5   6    7    8    9   10
0       A   10001  053  036  28  16  44  177  NaN  NaN NaN
1       A   10002  058  037  42  35  40  212    P  NaN NaN
2       A   10003  072  056  71  55  70  324    P  NaN NaN
3       A   10004  087  064  83  58  65  357    P  NaN NaN
4       A   10005  059  045  50  35  48  237    P  NaN NaN
...    ..     ...  ...  ...  ..  ..  ..  ...  ...  ...  ..
185662  C  199995  053  034  26  24  44  181  NaN  NaN NaN
185663  C  199996  051  038  24  15  41  169  NaN  NaN NaN
185664  C  199997  049  039  12  20  24  144  NaN  NaN NaN
185665  C  199998  033  036  22  15  35  141  NaN  NaN NaN
185666  C  199999  017  014  15  14  20   80  NaN  NaN NaN

[185667 rows x 11 columns]

<ipython-input-5-c0fc4ee1c5e8>:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  sslc = pd.read_csv('marks.txt', sep=';', header=None, index_col=None)

In [ ]:
#returns no of data(cells) (rows * columns) in data frame
sslc.size

2042337

In [ ]:
#Returns total number of not null rows in each columns
sslc.count()

0     185667
1     185667
2     185667
3     185667
4     185667
5     185667
6     185667
7     185667
8     159072
9        113
10         0
dtype: int64

In [ ]:
#total (rows, columns)
sslc.shape

(185667, 11)

In [ ]:
sslc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185667 entries, 0 to 185666
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       185667 non-null  object
 1   1       185667 non-null  int64
 2   2       185667 non-null  object
 3   3       185667 non-null  object
 4   4       185667 non-null  object
 5   5       185667 non-null  object
 6   6       185667 non-null  object
 7   7       185667 non-null  object
 8   8       159072 non-null  object
 9   9       113 non-null     object
 10  10      0 non-null       float64
dtypes: float64(1), int64(1), object(9)
memory usage: 15.6+ MB

In [ ]:
#number of unique records in data frame
sslc.nunique()

0          6
1     185667
2         96
3         95
4         99
5         98
6         97
7        882
8          1
9          1
10         0
dtype: int64

In [ ]:
#describe obly works on integer or flot columns
sslc.describe()

                  1    10
count  185667.000000  0.0
mean   105014.949043  NaN
std     54921.152696  NaN
min     10001.000000  NaN
25%     57314.500000  NaN
50%    105291.000000  NaN
75%    152581.500000  NaN
max    199999.000000  NaN

In [ ]:
sslc.describe(include=[object])

             0       2       3       4       5       6       7       8    9
count   185667  185667  185667  185667  185667  185667  185667  159072  113
unique       6      96      95      99      98      97     882       1    1
top          B     085     035      35      35      35     278       P    W
freq     41341    5989    6703   12842   25723    5334     592  159072  113

In [ ]:
sslc.columns = ['region', 'roll_number' , 'fl','sl','math','sci','ss','total','pass','withheld','extra']

In [ ]:
# returns specific row based on integer location( default index)
sslc.iloc[2]

region             A
roll_number    10003
fl               072
sl               056
math              71
sci               55
ss                70
total            324
pass               P
withheld         NaN
extra            NaN
Name: 2, dtype: object

In [ ]:
sslc.set_index('roll_number', inplace=True)

In [ ]:
sslc.head()

            region   fl   sl math sci  ss total pass withheld  extra
roll_number
10001            A  053  036   28  16  44   177  NaN      NaN    NaN
10002            A  058  037   42  35  40   212    P      NaN    NaN
10003            A  072  056   71  55  70   324    P      NaN    NaN
10004            A  087  064   83  58  65   357    P      NaN    NaN
10005            A  059  045   50  35  48   237    P      NaN    NaN

In [ ]:
sslc.loc[10003]

region        A
fl          072
sl          056
math         71
sci          55
ss           70
total       324
pass          P
withheld    NaN
extra       NaN
Name: 10003, dtype: object